config/routes.rb
RemoteRecognizer::Application.routes.draw do
  root        to: 'customers#index'
  # Resources access.
  resources   :customers do
    resources   :documents
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible       :file_number, :email, :first_name, :last_name, :address, :city, :zip
  has_many              :documents,
                          dependent:    :destroy


  # eMail validation.
  VALID_EMAIL_REGEX     = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates             :email,
                          uniqueness:   { case_sensitive: false },
                          format:       { with: VALID_EMAIL_REGEX, message: 'must be a valid email address' }

  # File number validations.
  validates             :file_number,
                          length:       { minimum: 3, maximum: 12 }
  # First / Last name validation.
  validates             :first_name,
                          length:       { minimum: 3 }
  validates             :last_name,
                          length:       { minimum: 3 }
  # Address / State / ZIP validation.
  VALID_ZIP_REGEX       = /^\d{5}$/
  validates             :address,
                          length:       { minimum: 3 }
  validates             :city,
                          length:       { minimum: 3 }
  validates             :zip,
                          format:       { with: VALID_ZIP_REGEX, message: "should be in the form 12345" }

  after_create          :create_template_documents
  def create_template_documents
    documents.find_or_create_by_kind({
        kind:           Document::Kinds[:identity_card],
        status:         Document::Statuses[:invalid]
      }, without_protection: true)
    documents.find_or_create_by_kind({
        kind:           Document::Kinds[:bank_account],
        status:         Document::Statuses[:invalid]
      }, without_protection: true)
    documents.find_or_create_by_kind({
        kind:           Document::Kinds[:address_proof],
        status:         Document::Statuses[:invalid]
      }, without_protection: true)
    documents.find_or_create_by_kind({
        kind:           Document::Kinds[:bank_check],
        status:         Document::Statuses[:invalid]
      }, without_protection: true)
  end
end

app/models/document.rb
require 'enumeration'

class Document < ActiveRecord::Base
  attr_accessible               :picture
  belongs_to                    :customer

  # Status field is integer, let's use an enum.
  class Statuses < Enumeration
    add :invalid,        0
    add :incomplete,     1
    add :valid,          2
  end

  # Status field is integer, let's use an enum.
  class Kinds < Enumeration
    add :unknown,        0
    add :identity_card,  1
    add :bank_account,   2
    add :address_proof,  3
    add :bank_check,     4
  end

  include Paperclip::Glue
  has_attached_file             :picture,
                                  default_url:  '/assets/Missing.png',
                                  styles:       { medium: '500x500>', thumb:  '32x32#' }

  before_save                   :setup_status_and_kind
  before_update                 :setup_status_and_kind
  def setup_status_and_kind
    self.status, self.results   = *if picture_file_name
      case picture_file_name.split('.').first
        when 'CNI18_N_R'
          customer.first_name     = 'Jean'
          customer.last_name      = 'BARRET-CASTAN'
          customer.address        = '124 ROUTE DE CROBEIL'
          customer.city           = 'SAINTE-GENEVIEVE-DES-BOIS'
          customer.zip            = '91000'
          customer.save
          [ Statuses[:valid],       'This document matches the prerequisites.' ]
        when 'CHK18'        then  [ Statuses[:valid],       'This document matches the prerequisites.' ]
        when 'RIB18'        then  [ Statuses[:valid],       'This document matches the prerequisites.' ]
        when 'CHK19'        then  [ Statuses[:invalid],     'The account information from this check doesn\'t match the account number.' ]
        else                      [ Statuses[:valid],       'This document matches the prerequisites.' ]
      end
    else
      [ Statuses[:incomplete], 'The document has no picture yet.' ]
    end
  end

  def status_picture_url
    return 'Incomplete.png' unless kind
    case status
      when Statuses[:invalid]         then 'Invalid.png'
      when Statuses[:incomplete]      then 'Incomplete.png'
      when Statuses[:valid]           then 'Valid.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include AjaxHelper::Renderer
  respond_to          :html, :js
  before_filter       :before_all

  def index
    respond_with @customers
  end

  def show
    respond_with @customer
  end

  def new
    @customer=Customer.new
    respond_to do |f|
      f.js { render_ajax }
      f.html { respond_with @customer }
    end
  end
  def create
    @customer         = Customer.new params[:customer]
    respond_to do |f|
      if @customer.save
        f.js { render_ajax }
        f.html { respond_with @customer }
      else
        f.js { render_ajax action: :new }
        f.html { render_action :new }
      end
    end
  end

  def edit
    respond_to do |f|
      f.js { render_ajax }
      f.html { respond_with @customer }
    end
  end
  def update
    respond_to do |f|
      if @customer.update_attributes(params[:customer])
        f.js { render_ajax }
        f.html { respond_with @customer }
      else
        f.js { render_ajax action: :edit }
        f.html { render action: :edit }
      end
    end
  end
  def destroy
    @customer.destroy
    respond_to do |f|
      f.js { render_ajax }
      f.html { redirect_to @customer }
    end
  end

  private
    def before_all
      @customer   = Customer.find params[:id] if params.has_key? :id
      @customers  = Customer.all unless params.has_key? :id
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include AjaxHelper::Renderer
  respond_to          :html, :js
  before_filter       :before_all
  def index
    respond_with @documents
  end
  def show
    respond_with @document
  end
  def new
    respond_to do |f|
      @document=Document.new
      f.js { render_ajax }
      f.html { respond_with @document }
    end
  end
  def create
    @document         = @customer.documents.new params[:document]
    @document.status  = Document::Statuses[:valid]
    @document.kind    = Document::Kinds[:check]
    respond_to do |f|
      if @document.save
        f.js { render_ajax }
        f.html { respond_with @customer }
      else
        f.js { render_ajax action: :new }
        f.html { render_action :new }
      end
    end
  end
  def edit
    respond_to do |f|
      f.js { render_ajax }
      f.html { respond_with @customer,@document }
    end
  end
  def update
    respond_to do |f|
      if @document.update_attributes(params[:document])
        f.js { render_ajax }
        f.html { respond_with @customer }
      else
        f.js { render_ajax action: :edit }
        f.html { render action: :edit }
      end
    end
  end
  def destroy
    @document.destroy
    respond_to do |f|
      f.js { render_ajax }
      f.html { redirect_to @customer }
    end
  end

  private
    def before_all
      @customer   = Customer.find params[:customer_id]
      @document   = @customer.documents.find params[:id] if params.has_key? :id
      @documents  = @customer.documents unless params.has_key? :id
    end
end

app/helpers/ajax_helper.rb
module AjaxHelper
  module Renderer
    def render_ajax (locals={})
      locals[:object_name]  ||= controller_name.sub('Controller', '').singularize
      locals[:object]       ||= instance_variable_get "@#{locals[:object_name]}"
      locals[:singular]     ||= locals[:object].class.name.underscore
      locals[:plural]       ||= locals[:singular].pluralize
      locals[:action]       ||= action_name
      puts locals.inspect
      render partial: "shared/ajax/ajax_#{locals[:action]}", locals: locals
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title (page_title)
    base_title = 'Remote Recognizer'
    page_title.empty? ? base_title : "#{base_title} | #{page_title}"
  end

  def formated_email_for (usr)
    "#{usr.first_name} #{usr.last_name.upcase}<#{usr.email}>"
  end
  def formated_email_link_for (usr)
    return "<a href=\"mailto:#{formated_email_for(usr)}\">#{usr.first_name} #{usr.last_name.upcase}</a>"
  end

  def button_text_for (ctrlr)
    act = ctrlr.action_name=='new' ? 'Create' : 'Update'
    "#{ act } #{ctrlr.class.name.sub("Controller", "").singularize}"
  end
end

app/views/customers/_customer.haml
=content_tag_for :li, customer, class: 'row-fluid' do
  %span.content.span10
    #{formated_email_link_for(customer).html_safe}
    %span.secondary
      #{pluralize(customer.documents.delete_if{|d| d.status==Document::Statuses[:valid] }.size, 'missing document')}
  %span.btn-toolbar.span2
    %span.btn-bar.pull-right
      %span.btn-group
        = link_to 'Delete', customer, remote: true, method: :delete, class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure?' }
      %span.btn-group
        #{link_to 'Show', customer_path(customer), class: 'btn btn-mini'}

app/views/customers/_form.haml
=form_for @customer, remote: true, html: { class: 'well form-horizontal' } do |f|
  %fieldset
    %legend #{controller.action_name.capitalize} Customer
    =render 'shared/error_messages', object: @customer

    -if controller.action_name=='new' || controller.action_name=='create' then
      .control-group
        =f.label :file_number, class: 'control-label'
        .controls
          =f.text_field :file_number, placeholder: '3892AC8DF'

    -else
      .control-group
        =f.label :email, class: 'control-label'
        .controls
          =f.text_field :email, placeholder: 'Berry.STRAW@Fruits.shake'

      .control-group
        =f.label :first_name, class: 'control-label'
        .controls
          =f.text_field :first_name, placeholder: 'Berry'

      .control-group
        =f.label :last_name, class: 'control-label'
        .controls
          =f.text_field :last_name, placeholder: 'STRAW'

      .control-group
        =f.label :address, class: 'control-label'
        .controls
          =f.text_field :address, placeholder: '3, Basket St.'

      .control-group
        =f.label :city, class: 'control-label'
        .controls
          =f.text_field :city, placeholder: 'Smoothie City'

      .control-group
        =f.label :zip, class: 'control-label'
        .controls
          =f.text_field :zip, placeholder: '95014'

    .form-actions
      =f.submit button_text_for(controller), class: 'btn btn-primary'

app/views/customers/edit.haml
- provide(:title, 'Account Edition')
.row
  .span8.offset2= render 'form'

app/views/customers/index.haml
- provide(:title, 'Customers')
%section.row-fluid
  %h3.span11 Customers
  .span1= link_to 'New', new_customer_path, remote: true, class: 'btn btn-mini pull-right'
%ul#customers.listing= render @customers

app/views/customers/new.haml
- provide(:title, 'New Customer')
.row
  .span8.offset2= render 'form'

app/views/customers/show.haml
- provide(:title, @customer.email)
.row-fluid
  .column.span3
    %section.row-fluid
      %h3.span10= formated_email_link_for(@customer).html_safe
      .span2= link_to 'Edit', edit_customer_path(@customer), remote: true, class: 'btn btn-mini pull-right'
    .row-fluid
      %p #{@customer.address}
      %p #{@customer.city}, #{@customer.zip}
  .column.span9
    = render 'documents/documents_section', customer: @customer

app/views/documents/_document.haml
=content_tag_for :li, document, class: 'row-fluid' do
  %span.content.span11
    %span.pictures.document-status-bubbler{ data: { url: document.picture.url(:medium), text: document.results } }
      =image_tag document.status_picture_url, size: '16x16'
      =image_tag document.picture.url(:thumb), size: '32x32'
    %span.text
      #{Document::Kinds.hash.invert[document.kind || 0].to_s.humanize}
  %span.btn-toolbar.span1
    %span.btn-group.pull-right
      = link_to 'Edit', edit_customer_document_path(document.customer, document), remote: true, class: 'btn btn-mini'

app/views/documents/_documents_section.haml
%section.row-fluid
  %h3.span11 Documents
  %span.btn-toolbar.span1
    %span.btn-group.pull-right
      .span3= link_to 'New', new_customer_document_path(customer), remote: true, class: 'btn btn-mini'
%ul#documents.listing= render customer.documents, customer: customer

app/views/documents/_form.haml
=form_for [ @customer, @document ], remote: true, html: { multipart: true, class: 'well form-horizontal' } do |f|
  %fieldset

    %legend #{controller.action_name.capitalize} Document
    =render 'shared/error_messages', object: @document

    / .control-group
    /   =f.label :status, class: 'control-label'
    /   .controls
    /     =f.select :status, Document::Statuses.hash.collect { |k,v| [ k.to_s.humanize, v ] }

    / .control-group
    /   =f.label :kind, class: 'control-label'
    /   .controls
    /     =f.select :kind, Document::Kinds.hash.collect { |k,v| [ k.to_s.humanize, v ] }

    .control-group
      =f.label :picture, class: 'control-label'
      .controls
        =f.file_field :picture, multiple: false, placeholder: 'Picture...'

    =image_tag @document.picture.url if @document.picture_file_name

    .form-actions=f.submit button_text_for(controller), class: 'btn btn-primary'

app/views/documents/edit.haml
- provide :title, 'Document Edition'
.row-fluid
  .span10.offset1= render 'form'

app/views/documents/new.haml
- provide(:title, 'Document Creation')
.row-fluid
  .span10.offset1= render 'form'

app/views/documents/show.haml
- provide(:title, @document.file_name)
.row-fluid
  .column.span5
    %section.row-fluid
      %h3.span9= @document.status
      .span3= link_to 'Edit', edit_customer_document_path(@customer,@document), class: 'btn btn-mini pull-right'

app/views/layouts/_footer.haml
%footer
  %small Copyright ATOS 2012. All rights reserved.

app/views/layouts/_header.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      = link_to 'Remote Recognizer', root_path, class: 'brand'
      %nav
        %ul.nav
        %ul.nav.pull-right
          = render 'layouts/menu'

app/views/layouts/_menu.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    Actions
    %b.caret
  %ul.dropdown-menu
    %li= link_to 'Customers', customers_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title= full_title yield(:title)
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, msg|
        %div{:class => "alert alert-#{key}", :id => "msg-#{key}"}
          %a.close{"data-dismiss" => "alert", :href => "#"} ×
          %p
            = msg
        :javascript
          if(' key ' != 'error') {
            $('#msg- key ').delay(1500).fadeOut(1000);
          }

      #modal-editor.modal.hide.fade
        .modal-header
          %a.close{"data-dismiss" => "modal", :href => "#"} ×
          %h3 Form
          #modal-editor-body.modal-body

      #body-content
        = yield
      = render 'layouts/footer'
      = debug params if Rails.env.development?

app/views/shared/_error_messages.haml
- if object.errors.any?
  #error_explanation
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg